Bionic Support and bug fixes
genesis-community/cf-app-autoscaler-genesis-kit pull request #12
Opened 2022-01-12 10:27 UTC by itsouvalas

# Features

* Using upstream 4.0.0
* Added bionic support on all instances

# Bug Fixes

* Fixes issue where pull upstream would fail to retrieve the corresponding release
* Fixes issue where the overlay would ignore the deployment and network provided for nats under bosh-dns-aliases addons and the deployment for route registrar job under specific instance groups

shoutout to @norman-abramovitz and @fearoffish for joining the overlay issue troubleshooting process

2022-01-16 23:35 UTC, dennisjbell requested changes
Spec tests were not regenerated.  Tests should also be added for ten year certs, mysql and external postgres databases and "all" (as many valid features turned on at once).

2022-01-17 07:20 UTC, dennisjbell commented
I have added spec tests for multiple scenarios in PR https://github.com/genesis-community/cf-app-autoscaler-genesis-kit/pull/13 -- please merge that PR first, then rebase against it.  Run spec tests on the updates and confirm differences are expected.

2022-01-18 18:59 UTC, xiujiao commented
> I have added spec tests for multiple scenarios in PR #13 -- please merge that PR first, then rebase against it. Run spec tests on the updates and confirm differences are expected.

Merged

2022-01-18 19:04 UTC, xiujiao commented
> Spec tests were not regenerated. Tests should also be added for ten year certs, mysql and external postgres databases and "all" (as many valid features turned on at once).

Good point!  @itsouvalas mentioned there is some issue with MySQL.

2022-01-19 11:29 UTC, itsouvalas commented
Currently working on specs. I'll mark it ready for review once they are passing.

2022-01-19 12:21 UTC, itsouvalas commented
Rebased and accepted changes. Added missing health_password records on credhub files. Shoutout to @fearoffish for pairing on the credhub keys

2022-01-20 17:08 UTC, dennisjbell approved these changes
looks good, just confirm the sha256:... as a value for the releases[].sha1 field.  Seems hackey as hell, but that doesn't mean its wrong

2022-01-20 17:08 UTC, dennisjbell commented on spec/results/mysql.yml
> +  sha1: sha256:031cf5600158f44762c747a1f8648b7cebca876d4297dd9e2ce3b51b36ccd476
Please confirm this is correct -- looks suspicious...

2022-01-21 10:06 UTC, fearoffish commented on spec/results/mysql.yml
> +  sha1: sha256:031cf5600158f44762c747a1f8648b7cebca876d4297dd9e2ce3b51b36ccd476
Can confirm it is correct. The `sha1` field can be used for all sha values and @itsouvalas and I also checked the sha value is correct.

2022-01-21 10:07 UTC, fearoffish commented on spec/results/mysql.yml
> +  sha1: sha256:031cf5600158f44762c747a1f8648b7cebca876d4297dd9e2ce3b51b36ccd476
Side note: there was a discussion about it here: https://github.com/cloudfoundry/bosh-cli/issues/272#issuecomment-317042705

2022-01-26 15:04 UTC, merged